#config_version=5
##! mode: skillshot

mode:
  start_events: ball_started
  stop_events:
    - skillshot_stop
    - skill_fail
  priority: 500

variable_player:
  mode_skillshot_started:
    is_skillshot_active:
      int: 1
      action: set
  mode_skillshot_will_stop:
    is_skillshot_active:
      int: 0
      action: set
     
  skill_success_full:
    score: current_player.pts_skillshot_full
  skill_success_partial:
    score: current_player.pts_skillshot_partial

sound_player:
  skill_success_full:
    voice_soberasabird:
      action: play
  skill_success_partial:
    voice_soberasabird:
      action: play

slides:
  slide_skillshot_intro:
    widgets:
    - type: image
      image: skillshottitle
      anchor_x: right
      anchor_y: top
      x: right - 25
      y: top - 15
    - type: image
      image: hitwhengreen
      anchor_x: left
      anchor_y: top
      x: left + 450
      y: top - 325
    - type: image
      image: arrow-down
      anchor_x: center
      anchor_y: center
      x: 858
      y: 240
      opacity: 0
      animations:
        show_slide:
          - property: opacity
            value: 1
            duration: 0.5s
            easing: in_out_quint
          - property: opacity
            value: 0
            duration: 0.5s
            repeat: true
            easing: in_out_quint
    - type: image
      image: arrow-down
      anchor_x: center
      anchor_y: center
      x: 730
      y: 270
      opacity: 0
      animations:
        show_slide:
          - property: opacity
            value: 1
            duration: 0.5s
            easing: in_out_quint
          - property: opacity
            value: 0
            duration: 0.5s
            repeat: true
            easing: in_out_quint
    - type: video
      video: skillshot-intro
      anchor_x: center
      anchor_y: center
      height: 400
      width: 711
      end_behavior: loop
  slide_skillshot_text:
    widgets:
    - type: image
      image: MiniText-TimedSkillShot
      animations:
        show_slide:
          - property: opacity
            value: 1
            duration: 0.5s
            easing: in_out_quint
          - property: opacity
            value: 0
            duration: 0.5s
            repeat: true
            easing: in_out_quint
    - type: image
      image: minibg
  slide_skillshot_success_full:
    widgets:
    - type: text
      text: Super Skill Shot
      font_size: 150
      font_name: druillet
      anchor_x: center
      anchor_y: top
      x: middle
      y: top - 35
      color: 008ce5ff
    - type: text
      text: SUCCESS
      font_size: 150
      font_name: druillet
      anchor_x: center
      anchor_y: top
      x: middle
      y: top - 210
      color: green
    - type: text
      text: (player|pts_skillshot_full)
      number_grouping: true
      min_digits: 1
      font_size: 10
      font_name: druillet
      anchor_x: center
      anchor_y: top
      x: middle
      y: top - 425
      color: 008ce5ff
      animations:
        show_slide:
          - property: font_size
            value: 200
            duration: .5s
    - type: video
      video: bubbles
  slide_skillshot_success_partial:
    widgets:
    - type: text
      text: Skill Shot
      font_size: 150
      font_name: druillet
      anchor_x: center
      anchor_y: top
      x: middle
      y: top - 35
      color: 008ce5ff
    - type: text
      text: SUCCESS
      font_size: 150
      font_name: druillet
      anchor_x: center
      anchor_y: top
      x: middle
      y: top - 210
      color: green
    - type: text
      text: (player|pts_skillshot_partial)
      number_grouping: true
      min_digits: 1
      font_size: 10
      font_name: druillet
      anchor_x: center
      anchor_y: top
      x: middle
      y: top - 425
      color: 008ce5ff
      animations:
        show_slide:
          - property: font_size
            value: 200
            duration: .5s
    - type: video
      video: bubbles

slide_player:
  mode_skillshot_started:
    slide_skillshot_text:
      target: mini
      priority: 1000
  skill_success_full:
    slide_skillshot_success_full:
      target: main
      priority: 1000
      expire: 3s
  skill_success_partial:
    slide_skillshot_success_partial:
      target: main
      priority: 1000
      expire: 3s

event_player:
  mode_skillshot_started: add_skillshot_widgets
  slide_slide_skillshot_success_full_removed: skillshot_stop
  slide_slide_skillshot_success_partial_removed: skillshot_stop

  shot_plunger_lane_exit_hit{device.lights.gi_back6.color[1] > 0}: skill_success_full
  shot_plunger_lane_exit_hit{device.lights.gi_back5.color[1] > 0 and device.lights.gi_back6.color[1] == 0}: skill_success_partial
  shot_plunger_lane_exit_hit{device.lights.gi_back6.color[1]==0 and device.lights.gi_back5.color[1]==0}: skill_fail

shows:
  show_gi_back_chase:
    - duration: .25
      lights:
        gi_back1:
          color: red
          fade: 0ms
        gi_back2:
          color: off
          fade: 0ms
        gi_back3:
          color: off
          fade: 0ms
        gi_back4:
          color: off
          fade: 0ms
        gi_back5:
          color: off
          fade: 0ms
        gi_back6:
          color: off
          fade: 0ms
      
    - duration: .25
      lights:
        gi_back1:
          color: off
          fade: 0ms
        gi_back2:
          color: red
          fade: 0ms
        gi_back3:
          color: off
          fade: 0ms
        gi_back4:
          color: off
          fade: 0ms
        gi_back5:
          color: off
          fade: 0ms
        gi_back6:
          color: off
          fade: 0ms

    - duration: .25
      lights:
        gi_back1:
          color: off
          fade: 0ms
        gi_back2:
          color: off
          fade: 0ms
        gi_back3:
          color: red
          fade: 0ms
        gi_back4:
          color: off
          fade: 0ms
        gi_back5:
          color: off
          fade: 0ms
        gi_back6:
          color: off
          fade: 0ms
    - duration: .25
      lights:
        gi_back1:
          color: off
          fade: 0ms
        gi_back2:
          color: off
          fade: 0ms
        gi_back3:
          color: off
          fade: 0ms
        gi_back4:
          color: red
          fade: 0ms
        gi_back5:
          color: off
          fade: 0ms
        gi_back6:
          color: off
          fade: 0ms
    - duration: .25
      lights:
        gi_back1:
          color: off
          fade: 0ms
        gi_back2:
          color: off
          fade: 0ms
        gi_back3:
          color: off
          fade: 0ms
        gi_back4:
          color: off
          fade: 0ms
        gi_back5:
          color: green
          fade: 0ms
        gi_back6:
          color: off
          fade: 0ms
    - duration: .25
      lights:
        gi_back1:
          color: off
          fade: 0ms
        gi_back2:
          color: off
          fade: 0ms
        gi_back3:
          color: off
          fade: 0ms
        gi_back4:
          color: off
          fade: 0ms
        gi_back5:
          color: off
          fade: 0ms
        gi_back6:
          color: green
          fade: 0ms

show_player:
  mode_skillshot_started:
    show_gi_back_chase:
      loops: -1

timers:
  skillshot_timeout:
    start_value: 0
    end_value: 5     # set the timeout of your skill shot here
    direction: up
    tick_interval: 1s
    start_running: false
    control_events:
      - action: start
        event: balldevice_bd_plunger_lane_ball_eject_success  # replace "plunger_lane" with the name of your plunger device
