#config_version=5

# sound_player:
#   play_intro:
#     intro:
#       action: play
#       loops: 0
#       events_when_stopped: intro_complete
#   # intro_complete:
#   #   introrepeat:
#   #     action: play
#   #     loops: -1
#   mode_attract_will_stop:
#     intro:
#       action: stop
  # mode_attract_will_stop.1:
  #   introrepeat:
  #     action: stop

shows:
  chase_tavern_rwb:
    - duration: 1s
      shows:
        chase_tavern:
          loops: 0
          speed: 6
          show_tokens:
            color: red
    - duration: 1s
      shows:
        chase_tavern:
          loops: 0
          speed: 6
          show_tokens:
            color: white
    - duration: 1s
      shows:
        chase_tavern:
          loops: 0
          speed: 6
          show_tokens:
            color: blue
  chase_arrows_rwb:
    - duration: 1s
      shows:
        attract_chase_arrows:
          loops: 0
          speed: 8
          show_tokens:
            color: red
    - duration: 1s
      shows:
        attract_chase_arrows:
          loops: 0
          speed: 8
          show_tokens:
            color: white
    - duration: 1s
      shows:
        attract_chase_arrows:
          loops: 0
          speed: 8
          show_tokens:
            color: blue
  chase_house_rwb:
    - duration: 1s
      shows:
        attract_chase_house:
          loops: 0
          speed: 10
          show_tokens:
            color: red
    - duration: 1s
      shows:
        attract_chase_house:
          loops: 0
          speed: 10
          show_tokens:
            color: white
    - duration: 1s
      shows:
        attract_chase_house:
          loops: 0
          speed: 10
          show_tokens:
            color: blue
  chase_popo_rwb:
    - duration: 1s
      shows:
        chase_popo:
          loops: 0
          speed: 6
          show_tokens:
            color: red
    - duration: 1s
      shows:
        chase_popo:
          loops: 0
          speed: 6
          show_tokens:
            color: white
    - duration: 1s
      shows:
        chase_popo:
          loops: 0
          speed: 6
          show_tokens:
            color: blue
  chase_lowerthird_rwb:
    - duration: 1s
      shows:
        attract_chase_lowerthird:
          loops: 0
          speed: 10
          show_tokens:
            color: red
    - duration: 1s
      shows:
        attract_chase_lowerthird:
          loops: 0
          speed: 10
          show_tokens:
            color: white
    - duration: 1s
      shows:
        attract_chase_lowerthird:
          loops: 0
          speed: 10
          show_tokens:
            color: blue
  chase_quarters_white:
    - duration: 1s
      shows:
        chase_quarters:
          loops: 0
          speed: 5
          show_tokens:
            color: white
  chase_bonus_rwb:
    - duration: 1s
      shows:
        attract_chase_bonus:
          loops: 0
          speed: 6
          show_tokens:
            color: red
    - duration: 1s
      shows:
        attract_chase_bonus:
          loops: 0
          speed: 6
          show_tokens:
            color: white
    - duration: 1s
      shows:
        attract_chase_bonus:
          loops: 0
          speed: 6
          show_tokens:
            color: blue
  brackets_white:
    - duration: 2s
      shows:
        attract_brackets:
          loops: 0
          speed: 5
          show_tokens:
            color: white

show_player:
  mode_attract_started:
    attract_init_lights:
      loops: 0
  # mode_attract_started.1:
  #   led_test:
  #     loops: -1

  mode_attract_started.1:
    attract_display_main:
      loops: -1
  mode_attract_started.2:
    attract_upf:
      loops: -1
      speed: 4
  mode_attract_started.4:
    chase_lowerthird_rwb:
      loops: -1
  mode_attract_started.5:
    chase_tavern_rwb:
      loops: -1
  mode_attract_started.6:
    chase_popo_rwb:
      loops: -1
  mode_attract_started.7:
    chase_arrows_rwb:
      loops: -1
  mode_attract_started.8:
    chase_house_rwb:
      loops: -1
  mode_attract_started.9:
    chase_quarters_white:
      loops: -1
  mode_attract_started.10:
    brackets_white:
      loops: -1     
  mode_attract_started.11:
    chase_bonus_rwb:
      loops: -1       
  mode_attract_started.12:
    attract_ball_locks:
      loops: -1
      speed: 4
  mode_attract_started.13:
    attract_modes:
      loops: -1
  mode_attract_started.14:
    pongtable_releaseall_show:
      loops: 0
  mode_attract_started.15:
    attract_pops:
      loops: -1
  mode_attract_started.16:
    attract_gi:
      speed: 1
      loops: -1
  mode_attract_started.17:
    attract_gi_back:
      speed: 2
      loops: -1
  mode_attract_started.18:
    attract_startbutton:
      speed: 5
      loops: -1
  mode_attract_started.19:
    attract_display_mini:
      loops: -1
  mode_attract_started.20:
    attract_audio:
      loops: -1
