#config_version=5

sound_player:
  mode_attract_started:
    intro:
      action: play
      loops: 0
      events_when_stopped: intro_complete
  intro_complete:
    introrepeat:
      action: play
      loops: -1
  mode_attract_will_stop:
    intro:
      action: stop
  mode_attract_will_stop.1:
    introrepeat:
      action: stop

show_player:
  mode_attract_started:
    attract_init_lights:
      loops: 0
  mode_attract_started.1:
    attract_display_loop:
      loops: -1
  mode_attract_started.2:
    attract_drinko:
      loops: -1
      speed: 4
  mode_attract_started.3:
    attract_beermug:
      loops: -1
      speed: 5
  mode_attract_started.4:
    attract_outerlights:
      loops: -1
      speed: 7
  mode_attract_started.5:
    attract_trojankeg:
      loops: -1
      speed: 1
  mode_attract_started.6:
    attract_slings:
      loops: -1
      speed: 2
  mode_attract_started.7:
    attract_arrows:
      loops: -1
      speed: 2   
  mode_attract_started.8:
    attract_bonuslocked:
      loops: -1
      speed: 4
  mode_attract_started.9:
    attract_modes:
      loops: -1
  mode_attract_started.10:
    pongtable_releaseall_show:
      loops: 0
  mode_attract_started.11:
    attract_pops:
      loops: -1
  mode_attract_started.12:
    attract_gi:
      speed: 1
      loops: -1
  mode_attract_started.13:
    attract_gi_back:
      speed: 2
      loops: -1
  mode_attract_started.14:
    attract_startbutton:
      speed: 5
      loops: -1
  
