#config_version=5
##! mode: multiball

mode:
  start_events: mode_base_started
  stop_events: game_ended

queue_relay_player:
  balldevice_bd_trough_ball_eject_attempt{current_player.is_showing_pongsink_slide == 1}:
    post: nothing
    wait_for: multiball_ready_for_next_ball
  balldevice_bd_trough_ball_eject_attempt{current_player.is_showing_popo_captured_slide == 1}:
    post: nothing
    wait_for: popo_ready_for_next_ball

shows:
  munich_multiball_enabled:
    - duration: 1
      lights:
        arrow_rimrules1: 008ce5          
        arrow_rimrules2: off          
        arrow_rimrules3: off          
        arrow_mode1: 008ce5          
        arrow_mode2: off          
        arrow_mode3: off          
    - duration: 1
      lights:
        arrow_rimrules1: 008ce5          
        arrow_rimrules2: 008ce5          
        arrow_rimrules3: off          
        arrow_mode1: 008ce5          
        arrow_mode2: 008ce5          
        arrow_mode3: off
    - duration: 1
      lights:
        arrow_rimrules1: 008ce5          
        arrow_rimrules2: 008ce5          
        arrow_rimrules3: 008ce5          
        arrow_mode1: 008ce5          
        arrow_mode2: 008ce5
        arrow_mode3: 008ce5          
    - duration: 1
      lights:
        arrow_rimrules1: off          
        arrow_rimrules2: 008ce5          
        arrow_rimrules3: 008ce5          
        arrow_mode1: off          
        arrow_mode2: 008ce5         
        arrow_mode3: 008ce5          
    - duration: 1
      lights:
        arrow_rimrules1: off          
        arrow_rimrules2: off          
        arrow_rimrules3: 008ce5          
        arrow_mode1: off          
        arrow_mode2: off          
        arrow_mode3: 008ce5
    - duration: 1
      lights:
        arrow_rimrules1: off          
        arrow_rimrules2: off          
        arrow_rimrules3: off          
        arrow_mode1: off          
        arrow_mode2: off          
        arrow_mode3: off  
  popo_multiball_enabled:
    - duration: 1
      lights:
        arrow_popo1: 008ce5          
        arrow_popo2: off          
        arrow_popo3: off        
    - duration: 1
      lights:
        arrow_popo1: 008ce5          
        arrow_popo2: 008ce5          
        arrow_popo3: off   
    - duration: 1
      lights:
        arrow_popo1: 008ce5          
        arrow_popo2: 008ce5          
        arrow_popo3: 008ce5       
    - duration: 1
      lights:
        arrow_popo1: off          
        arrow_popo2: 008ce5          
        arrow_popo3: 008ce5       
    - duration: 1
      lights:
        arrow_popo1: off          
        arrow_popo2: off          
        arrow_popo3: 008ce5   
    - duration: 1
      lights:
        arrow_popo1: off          
        arrow_popo2: off          
        arrow_popo3: off
  light_ball1_locked: 
    - duration: 1
      lights:
        ball1_locked: 008ce5
    - duration: 1
      lights:
        ball1_locked: off
    - duration: 1
      lights:
        ball1_locked: 008ce5
    - duration: 1
      lights:
        ball1_locked: off
    - duration: 1
      lights:
        ball1_locked: 008ce5
    - duration: 1
      lights:
        ball1_locked: off
    - duration: 1
      lights:
        ball1_locked: 008ce5
    - duration: 1
      lights:
        ball1_locked: off
    - duration: 1
      lights:
        ball1_locked: 008ce5
    - duration: -1
  light_ball2_locked:
    - duration: 1
      lights:
        ball2_locked: 008ce5
    - duration: 1
      lights:
        ball2_locked: off
    - duration: 1
      lights:
        ball2_locked: 008ce5
    - duration: 1
      lights:
        ball2_locked: off
    - duration: 1
      lights:
        ball2_locked: 008ce5
    - duration: 1
      lights:
        ball2_locked: off
    - duration: 1
      lights:
        ball2_locked: 008ce5
    - duration: 1
      lights:
        ball2_locked: off   
    - duration: 1
      lights:
        ball2_locked: 008ce5  
    - duration: -1
  clear_ballx_locked:
    - duration: 1
      lights:
        ball1_locked: off
        ball2_locked: off

slides:
  multiball_sink1_clean:
    widgets:
    - type: image
      image: background-flag
    - type: image
      image: MainText-Ball1Locked
      scale: .1
      anchor_x: center
      anchor_y: bottom
      x: middle
      y: bottom + 50
      animations:
        show_slide:
          - property: scale
            value: 1
            duration: 1.5s 
    - type: video
      video: pongsink1-clean
    expire: 5.5s
  multiball_sink1_adult:
    widgets:
    - type: image
      image: background-flag
    - type: image
      image: MainText-Ball1Locked
      scale: .1
      anchor_x: center
      anchor_y: bottom
      x: middle
      y: bottom + 50
      animations:
        show_slide:
          - property: scale
            value: 1
            duration: 1.5s 
    - type: video
      video: pongsink1-adult
    expire: 5.5s
  multiball_sink2:
    widgets:
    - type: image
      image: background-flag
    - type: image
      image: MainText-Ball2Locked
      scale: .1
      anchor_x: center
      anchor_y: bottom
      x: middle
      y: bottom + 50
      animations:
        show_slide:
          - property: scale
            value: 1
            duration: 1.5s 
    - type: video
      video: pongsink2
    expire: 3.5s
  popo_captured:
    widgets:
    - type: image
      image: background-flag
    - type: image
      image: MainText-PopoLocked
      scale: .1
      anchor_x: center
      anchor_y: bottom
      x: middle
      y: bottom + 50
      animations:
        show_slide:
          - property: scale
            value: 1
            duration: 1.5s 
    - type: video
      video: goodnightpopo
    expire: 4.75s
  multiball_slide:
    widgets:
    - type: image
      image: background-flag
    - type: image
      image: MainText-MunichMultiball
      scale: .1
      animations:
        show_slide:
          - property: scale
            value: 1
            duration: .5s
    - type: video
      video: bubbles
  multiball_slide_popo:
    widgets:
    - type: image
      image: background-flag
    - type: image
      image: MainText-PopoMultiball
      scale: .1
      animations:
        show_slide:
          - property: scale
            value: 1
            duration: .5s
    - type: video
      video: bubbles
  slide_mini_mb_shootsaucers:
    widgets:
    - type: image
      image: MiniText-ShootSaucers
      animations:
        show_slide:
          - property: opacity
            value: 1
            duration: 0.5s
            easing: in_out_quint
          - property: opacity
            value: 0
            duration: 0.5s
            repeat: true
            easing: in_out_quint
    - type: image
      image: beermug7

slide_player:
  multiball_sink1{device.switches.s_adult.state == 0}:
    multiball_sink1_clean:
      target: main
      priority: 5000
  multiball_sink1{device.switches.s_adult.state == 1}:
    multiball_sink1_adult:
      target: main
      priority: 5000
  shot_popo_captured_hit{device.state_machines.multiball_popo.state == "ready_for_capture"}:
    popo_captured:
      target: main
      priority: 5000
  
  start_multiball:
    multiball_slide:
      target: main
      priority: 5000
      expire: 3s
  shot_popo_released_hit{device.state_machines.multiball_popo.state == "ball_captured"}:
    multiball_slide_popo:
      target: main
      priority: 5000
      expire: 2.5s
  multiball_sink2:
    multiball_sink2:
      target: main
      priority: 5000
    slide_mini_mb_shootsaucers:
      target: mini
      priority: 2000

multiballs:
  pt_multiball:
    debug: true
    ball_count: 3
    shoot_again: 0s
    ball_count_type: total
    start_events: start_multiball
    ball_locks: bd_pongcup1, bd_pongcup2
  popo_multiball:
    debug: true
    ball_count: 2
    shoot_again: 0s
    ball_count_type: total
    start_events: start_multiball_popo
    ball_locks: bd_popo

multiball_locks:
  pt_lock1:
    debug: true
    lock_devices: bd_pongcup1
    balls_to_lock: 1
    locked_ball_counting_strategy: physical_only
    enable_events: enable_pt_lock
    disable_events: disable_ptlock1, start_multiball

  pt_lock2:
    debug: true
    lock_devices: bd_pongcup2
    balls_to_lock: 1
    locked_ball_counting_strategy: physical_only
    enable_events: enable_pt_lock
    disable_events: disable_ptlock2, start_multiball 

  popo_lock:
    debug: true
    lock_devices: bd_popo
    balls_to_lock: 1
    locked_ball_counting_strategy: physical_only
    enable_events: enable_popo_lock
    disable_events: start_multiball_popo, disable_popo_lock

state_machines:
  multiball:
    states:
      start:
        label: PongTable lock not enabled
      pongtable_cup1:
        label: PongTable Cup 1 Active
        events_when_started: enable_pt_lock
        show_when_active:
          show: pongtable_show
          show_tokens:
            cup: 1
          loops: 0
      pongtable_cup2:
        label: PongTable Cup 2 Active
        events_when_started: enable_pt_lock
        show_when_active:
          show: pongtable_show
          show_tokens:
            cup: 2
          loops: 0
      pongtable_cupNone:
        label: PongTable Cup None Active
        events_when_started: enable_pt_lock
        show_when_active:
          show: pongtable_show
          show_tokens:
            cup: 0
          loops: 0
      multiball_running:                      # pongcup balls are released automatically via MPF and are coordinated in machine config.yaml
        label: PongTable multiball running
        events_when_started: start_multiball

    transitions:
      # for reference - conditional event DEVICE. not DEVICES.
      #- source: start, lock_enabled
      #  target: multiball_available
      #  events: mode_multiball_started{device.ball_devices.bd_lock.balls==2}
      - source: start
        target: pongtable_cup1
        events: mode_multiball_started{device.switches.s_pongcup1.state == 0}
      - source: start
        target: pongtable_cup2
        events: mode_multiball_started{device.switches.s_pongcup1.state == 1 and device.switches.s_pongcup2.state == 0}
      - source: start
        target: pongtable_cupNone
        events: mode_multiball_started{device.switches.s_pongcup1.state == 1 and device.switches.s_pongcup2.state == 1}    

      - source: pongtable_cup1
        target: pongtable_cup2
        events: pongtable_movetocup2
      - source: pongtable_cup2
        target: pongtable_cupNone
        events: pongtable_movetocupNone
      - source: pongtable_cupNone
        target: multiball_running
        events: kicker_mode_eject, kicker_rimrules_eject
      - source: multiball_running
        target: pongtable_cup1
        events: multiball_pt_multiball_ended

  multiball_popo:
    states:
      start:
        label: Popo lock not enabled
      ready_for_capture:
        label: Popo capture area ready for ball
        events_when_started: enable_popo_lock
      ball_captured:
        label: Popo capture area contains a ball
        # show_when_active:
        #   show: pongtable_show
        #   show_tokens:
        #     cup: 2
        #   loops: 0
      do_not_capture:
        label: two balls already locked in pong table MB - do not hold onto any balls in popo
        events_when_started:
          - disable_popo_lock
          - eject_popo{device.switches.s_popo_captured.state == 1}    # eject ball if one is there
        # show_when_active:
        #   show: pongtable_show
        #   show_tokens:
        #     cup: 0
        #   loops: 0
      multiball_popo_running:
        label: Popo multiball running
        events_when_started: disable_popo_lock, start_multiball_popo

    transitions:
      # for reference - conditional event DEVICE. not DEVICES.
      #- source: start, lock_enabled
      #  target: multiball_available
      #  events: mode_multiball_started{device.ball_devices.bd_lock.balls==2}
      - source: start
        target: ready_for_capture
        events: mode_multiball_started{device.switches.s_popo_captured.state == 0 and device.switches.s_pongcup2.state == 0}
      - source: start
        target: ball_captured
        events: mode_multiball_started{device.switches.s_popo_captured.state == 1 and device.switches.s_pongcup2.state == 0}
      - source: start
        target: do_not_capture
        events: mode_multiball_started{device.switches.s_pongcup2.state == 1} 

      - source: ready_for_capture
        target: ball_captured
        events: shot_popo_captured_hit
      - source: ready_for_capture
        target: do_not_capture
        events: pongtable_movetocupNone             # do not want Popo to keep ball if we have 2 already locked in pong table

      - source: ball_captured
        target: multiball_popo_running
        events: slide_multiball_slide_popo_removed
      - source: ball_captured
        target: do_not_capture
        events: pongtable_movetocupNone             # do not want Popo to keep ball if we have 2 already locked in pong table

      - source: do_not_capture
        target: do_not_capture
        events: shot_popo_captured_hit
      - source: do_not_capture
        target: ready_for_capture
        events: multiball_pt_multiball_ended{device.switches.s_popo_captured.state == 0}
      - source: do_not_capture
        target: ball_captured
        events: multiball_pt_multiball_ended{device.switches.s_popo_captured.state == 1}  

      - source: multiball_popo_running
        target: ready_for_capture
        events: multiball_popo_multiball_ended{device.switches.s_pongcup2.state == 0}
      - source: multiball_popo_running
        target: do_not_capture
        events: multiball_popo_multiball_ended{device.switches.s_pongcup2.state == 1}

sound_player:
  slide_multiball_sink2_removed:
    voice_hitthesaucers_multiball:
      action: play
  slide_multiball_slide_active:
    voice_multiball:
      action: play
  slide_multiball_slide_popo_active:
    voice_multiball_popo:
      action: play
  # slide_popo_captured_active:
  #   introrepeat:
  #     action: stop
  # slide_popo_captured_removed:
  #   introrepeat:
  #     action: play
  #     loops: -1

show_player:
  slide_multiball_sink1_clean_active:
    light_ball1_locked:
      loops: 0
      speed: 4
      priority: 3000
  slide_multiball_sink1_adult_active:
    light_ball1_locked:
      loops: 0
      speed: 4
      priority: 3000
  slide_multiball_sink2_active:
    light_ball2_locked:
      loops: 0
      speed: 10
      priority: 3000  
  slide_multiball_sink2_removed:
    munich_multiball_enabled:
      loops: -1
      speed: 8
      priority: 3000
    light_ball2_locked:
      loops: 0
      priority: 3000
  start_multiball:
    munich_multiball_enabled:
      action: stop
    light_ball1_locked:
      action: stop
    light_ball2_locked:
      action: stop
  slide_popo_captured_removed:
    popo_multiball_enabled:
      loops: -1
      speed: 8
      priority: 3000
  start_multiball_popo:
    popo_multiball_enabled:
      action: stop
  mode_bonusv2_started:
    light_ball1_locked:
      action: stop
    light_ball2_locked:
      action: stop
    clear_ballx_locked:
      action: stop
  mode_dasboot_started:
    light_ball1_locked:
      action: stop
    light_ball2_locked:
      action: stop
    clear_ballx_locked:
      action: stop

event_player:
  shot_pongcup1_hit{device.state_machines.multiball.state != "multiball_running"}:
    - pongtable_movetocup2
    - multiball_sink1
  shot_pongcup2_hit{device.state_machines.multiball.state != "multiball_running" and device.switches.s_popo_captured.state == 0}:
    - pongtable_movetocupNone
    - multiball_sink2
  shot_pongcup2_hit{device.state_machines.multiball.state != "multiball_running" and device.switches.s_popo_captured.state == 1}: pongcup_2_release_show
  shot_pongcup2_hit{device.state_machines.multiball.state == "multiball_running" or device.switches.s_popo_captured.state == 1}: pongcup_2_release_show

  slide_multiball_sink1_clean_removed: multiball_ready_for_next_ball
  slide_multiball_sink1_adult_removed: multiball_ready_for_next_ball
  slide_multiball_sink2_removed: multiball_ready_for_next_ball
  slide_popo_captured_removed: popo_ready_for_next_ball
  slide_multiball_slide_removed{device.switches.s_kicker_rimrules.state == 1}: kicker_rimrules_eject
  slide_multiball_slide_removed{device.switches.s_kicker_mode.state == 1}: kicker_mode_eject

variable_player:
  slide_multiball_sink1_clean_created:
    is_showing_pongsink_slide:
      int: 1
      action: set
  slide_multiball_sink1_adult_created:
    is_showing_pongsink_slide:
      int: 1
      action: set
  slide_multiball_sink2_created:
    is_showing_pongsink_slide:
      int: 1
      action: set
  slide_multiball_sink1_clean_removed:
    is_showing_pongsink_slide:
      int: 0
      action: set
  slide_multiball_sink1_adult_removed:
    is_showing_pongsink_slide:
      int: 0
      action: set
  slide_multiball_sink2_removed:
    is_showing_pongsink_slide:
      int: 0
      action: set
  slide_popo_captured_created:
    is_showing_popo_captured_slide:
      int: 1
      action: set
  slide_popo_captured_removed:
    is_showing_popo_captured_slide:
      int: 0
      action: set

  start_multiball:
    score: current_player.pts_multiball

