#config_version=5
##! mode: popo

mode:
  start_events: start_mode_popo
  stop_events: stop_mode_popo, stop_missions
  events_when_started: mode_type_mission_started
  events_when_stopped: mode_type_mission_stopped
  priority: 300

counters:
  popo_release_switch:
    count_events: shot_popo_released_hit
    enable_events: mode_popo_started
    starting_count: 0
    count_complete_value: 4
    reset_on_complete: True

sound_player:
  rnd_hj:
    hj12:
      action: play
  rnd_bj:
    bj10:
      action: play
  rnd_zj:
    zj15:
      action: play
  counter_popo_release_switch_complete{device.switches.s_popo_captured.state == 0}:
    voice_oprecipe:
      action: play

event_player:
  shot_popo_released_hit{device.counters.popo_release_switch.value < 4 and device.switches.s_popo_captured.state == 0}: pick_hjbjzj   # play one of the 3 random HJ/BJ/ZJ sound clips as long as we don't have a ball in popo lock
  
random_event_player:
  pick_hjbjzj:
    events:
      - rnd_hj
      - rnd_bj
      - rnd_zj
  