#config_version=5
##! mode: popo

mode:
  start_events: start_mode_popo
  stop_events: stop_mode_popo, stop_missions
  events_when_started: mode_type_mission_started
  events_when_stopped: mode_type_mission_stopped
  priority: 300

counters:
  popo_release_switch:
    count_events: shot_popo_released_hit
    starting_count: 0
    count_complete_value: 4
    enable_events: mode_popo_started, reset_popo_release_switch_counter
    reset_on_complete: True

sound_player:
  rnd_hj:
    hj12:
      action: play
  rnd_bj:
    bj10:
      action: play
  rnd_zj:
    zj15:
      action: play
  logicblock_popo_release_switch_complete{device.switches.s_popo_captured.state == 0}:
    voice_oprecipe:
      action: play
      events_when_stopped: reset_popo_release_switch_counter

event_player:
  logicblock_popo_release_switch_updated{(value==1 or value==2 or value==3) and device.switches.s_popo_captured.state == 0}: pick_hjbjzj   # play one of the 3 random HJ/BJ/ZJ sound clips as long as we don't have a ball in popo lock
  
random_event_player:
  pick_hjbjzj:
    events:
      - rnd_hj
      - rnd_bj
      - rnd_zj
  
variable_player:
  rnd_hj:
    score: current_player.pts_hj
  rnd_bj:
    score: current_player.pts_bj
  rnd_zj:
    score: current_player.pts_zj
  logicblock_popo_release_switch_complete:
    score: current_player.pts_oprecipe