#config_version=5
##! mode: popo

mode:
  start_events: start_mode_popo
  stop_events: stop_mode_popo, stop_missions
  events_when_started: mode_type_mission_started
  events_when_stopped: mode_type_mission_stopped
  priority: 300

sound_player:
  shot_popo_captured_hit:
    voice_goodnightpopo:
      action: play
  shot_popo_released_hit:
    voice_oprecipe:
      action: play

event_player:
  # TODO: start multiball when we have balls in both pong cups and the third is captured here??
  shot_popo_captured_hit{device.switches.s_pongcup1.state == 1 and device.switches.s_pongcup2.state == 1}:    # only have 3 balls...release immediately
    events:
      - kicker_popo_eject
  shot_popo_released_hit{device.switches.s_popo_captured.state == 1}:
    events:
      - kicker_popo_eject

    