#config_version=5
##! mode: vs_breakout

# vs_breakout is a VS mode that pits player against a Breakout (r) style video game. Ping pong balls will fall from top at some angle,
#   and player uses flippers to move red solo cup back and forth to try and catch ball. 3 times and they win. A miss loses.
# pongball: 80x80 pixels
# cup: 160x209
# vs_breakout is started because one of the following occurred:
# 1. Player has not filled up mug (i.e. game theme mode not enabled) and has hit rimrules/mode saucers
#    a. 50% of the time, vs will start. Other 50% of the time, old original audio callout and popout will happen
# 2. Player has filled up mug (i.e. game theme mode is enabled) and has hit rimrules/mode saucers
#    a. 50% of the time, vs will start. Other 50% of the time, game theme mode will start

# Note: when copying, must update:
#  - mode start_events
#  - mode stop_events
#  - player_health_drain restart event (if applicable - otherwise delete)
#  - slide names in slides:
#  - slide names in slide_player:
#  - variable_player
#  - base mode vs_breakout_stopped: to update country insert
#  - shows: update show name
#  - show_player: update show names
#  - event player: choose random opponent
#  - update Field.yaml to include new VS challenge
#  - add mode to config.yaml

mode:
  start_events: start_mode_vs_breakout
  stop_events: game_ended, stop_mode_vs_breakout, start_mode_bonusv2

timers:
  update_frame:    # ensure that player health meter gets update *after* we update image location variables
    start_value: 1
    end_value: 0
    direction: down
    tick_interval: .1s
    control_events:
      - action: restart
        event: timer_framerate_complete
      - action: stop
        event: stop_update_timers

  framerate:     # called every 100ms. 1) update ball image based on x/y velocities. 2) update player cup left/right based on left/right flipper states
    start_value: 1
    end_value: 0
    direction: down
    tick_interval: .25s
    restart_on_complete: true
    control_events:
      - action: restart
        event: slide_vs_breakout_status_active
      - action: stop
        event: vs_result_win
      - action: stop
        event: stop_update_timers  

event_player:
  slide_vs_breakout_win_removed:
    stop_mode_vs_breakout
  slide_vs_breakout_lose_removed:
    stop_mode_vs_breakout
  mode_vs_breakout_stopping:
    kicker_mode_eject
  slide_vs_breakout_intro_removed{device.switches.s_kicker_rimrules.state==1}: kicker_rimrules_eject
  slide_vs_breakout_intro_removed{device.switches.s_kicker_mode.state==1}: kicker_mode_eject

  timer_framerate_complete{(device.switches.s_flipper_left.state == 1) and (current_player.cup_x > 130)}: move_cup_left    # can move left
  timer_framerate_complete{(device.switches.s_flipper_left.state == 1) and (current_player.cup_x <= 130)}: move_cup_far_left  # within limit of moving, so set to far left
  timer_framerate_complete{(device.switches.s_flipper_right.state == 1) and (current_player.cup_x < 1236)}: move_cup_right
  timer_framerate_complete{(device.switches.s_flipper_right.state == 1) and (current_player.cup_x >= 1236)}: move_cup_far_right
  timer_update_frame_complete:
    update_cup_x:
      new_x: {value: current_player.cup_x}

sound_player:
  slide_vs_breakout_intro_active:
    crowd:
      loops: -1
    introrepeat:
      action: stop
    boom_x4:
      action: play
  vs_result_win:
    crowd:
      action: stop
    voice_vs_win:
      loops: 0
  vs_result_lose:
    crowd:
      action: stop
    voice_vs_lose:
      loops:
  mode_vs_breakout_stopping:
    crowd:
      action: stop

shows:
  vs_breakout_flash_usa:
    - duration: 1
      lights:
        usa_left: (color)
        usa_right: (color)
    - duration: 1
      lights:
        usa_left: off
        usa_right: off
  vs_breakout_flash_opponent:
    - duration: 1
      lights:
        (led_left): (color)
        (led_right): (color)
    - duration: 1
      lights:
        (led_left): off
        (led_right): off

show_player:
  mode_vs_breakout_started:
    vs_breakout_flash_usa:
      loops: -1
      speed: 4
      show_tokens:
        color: yellow
    vs_breakout_flash_opponent:
      loops: -1
      speed: 4
      show_tokens:
        led_left: (current_player.opponent_left)
        led_right: (current_player.opponent_right)
        color: yellow
  mode_vs_breakout_stopping:
    vs_breakout_flash_usa:
      action: stop
    vs_breakout_flash_opponent:
      action: stop
  vs_result_win:
    vs_breakout_flash_usa:
      loops: -1
      speed: 4
      priority: 4000
      show_tokens:
        color: green
    vs_breakout_flash_opponent:
      loops: -1
      speed: 4
      priority: 4000
      show_tokens:
        led_left: (current_player.opponent_left)
        led_right: (current_player.opponent_right)
        color: red
  vs_result_lose:
    vs_breakout_flash_usa:
      loops: -1
      speed: 4
      priority: 4000
      show_tokens:
        color: red
    vs_breakout_flash_opponent:
      loops: -1
      speed: 4
      priority: 4000
      show_tokens:
        led_left: (current_player.opponent_left)
        led_right: (current_player.opponent_right)
        color: green

slides:
  vs_breakout_mini:
    - type: image
      image: TextOnMini-VideoMode
      animations:
        show_slide:
          - property: opacity
            value: 1
            duration: 0.5s
            easing: in_out_quint
          - property: opacity
            value: 0
            duration: 0.5s
            repeat: true
            easing: in_out_quint
    - type: image
      image: TextOnMini-CatchPongBalls
    - type: image
      image: minibg

  vs_breakout_intro:
    widgets:
    - type: text
      text: USA
      font_size: 25
      font_name: druillet
      anchor_x: left
      anchor_y: center
      x: left + 30
      y: middle + 200
      color: 008ce5ff
      animations:
        show_slide:
          - property: font_size
            value: 175
            duration: .5s
    - type: text
      text: vs
      font_size: 25
      font_name: druillet
      anchor_x: center
      anchor_y: center
      x: middle - 200
      y: middle + 200
      color: 008ce5ff
      opacity: 0
      animations:
        show_slide:
          - property: opacity
            value: 0
            duration: 1s
          - property: opacity
            value: 1
            duration: 0
            timing: after_previous
          - property: font_size
            value: 175
            duration: .25s
            timing: with_previous
    - type: text
      text: (opponent)
      font_size: 25
      font_name: druillet
      anchor_x: left
      anchor_y: center
      x: middle - 50
      y: middle + 200
      color: 008ce5ff
      opacity: 0
      animations:
        show_slide:
          - property: opacity
            value: 0
            duration: 2s
          - property: opacity
            value: 1
            duration: 0
            timing: after_previous
          - property: font_size
            value: 175
            duration: .25s
            timing: with_previous
    - type: text
      text: VIDEO MODE
      font_size: 25
      font_name: druillet
      anchor_x: middle
      anchor_y: middle
      x: middle
      y: middle - 59
      color: 008ce5ff
      opacity: 0
      animations:
        show_slide:
          - property: opacity
            value: 0
            duration: 3s
          - property: opacity
            value: 1
            duration: 0
            timing: after_previous
          - property: font_size
            value: 125
            duration: .25s
            timing: with_previous
    - type: text
      text: FLIPPERS MOVE CUP
      font_size: 25
      font_name: druillet
      anchor_x: middle
      anchor_y: middle
      x: middle
      y: middle - 250
      color: 008ce5ff
      opacity: 0
      animations:
        show_slide:
          - property: opacity
            value: 0
            duration: 3s
          - property: opacity
            value: 1
            duration: 0
            timing: after_previous
          - property: font_size
            value: 125
            duration: .25s
            timing: with_previous        
    - type: image
      image: background
  vs_breakout_status:
    widgets:
    - type: image
      image: pongball
      anchor_x: middle
      anchor_y: middle
      x: middle
      y: top - 75
      animations:
        update_ball_x:
          - property: x
            value: (new_x)
        update_ball_y:
          - property: y
            value: (new_y)    
    - type: image
      image: cup
      anchor_x: middle
      anchor_y: bottom
      x: middle
      y: bottom + 75
      animations:
        update_cup_x:
          - property: x
            value: (new_x)
    - type: image
      image: background

  vs_breakout_win:
    widgets:
    - type: text
      text: USA
      font_size: 25
      font_name: druillet
      anchor_x: left
      anchor_y: center
      x: left + 55
      y: middle + 200
      color: 008ce5ff
      animations:
        show_slide:
          - property: font_size
            value: 150
            duration: .5s
    - type: text
      text: vs
      font_size: 25
      font_name: druillet
      anchor_x: center
      anchor_y: center
      x: middle - 200
      y: middle + 200
      color: 008ce5ff
      opacity: 0
      animations:
        show_slide:
          - property: opacity
            value: 0
            duration: 1s
          - property: opacity
            value: 1
            duration: 0
            timing: after_previous
          - property: font_size
            value: 150
            duration: .25s
            timing: with_previous
    - type: text
      text: (opponent)
      font_size: 25
      font_name: druillet
      anchor_x: left
      anchor_y: center
      x: middle - 25
      y: middle + 200
      color: 008ce5ff
      opacity: 0
      animations:
        show_slide:
          - property: opacity
            value: 0
            duration: 2s
          - property: opacity
            value: 1
            duration: 0
            timing: after_previous
          - property: font_size
            value: 150
            duration: .25s
            timing: with_previous
    - type: text
      text: PLAYER WINS
      font_size: 25
      font_name: druillet
      anchor_x: center
      anchor_y: center
      x: middle
      y: middle
      color: green
      opacity: 0
      animations:
        show_slide:
          - property: opacity
            value: 0
            duration: 2.5s
          - property: opacity
            value: 1
            duration: 0
            timing: after_previous
          - property: font_size
            value: 150
            duration: .25s
            timing: with_previous
    - type: text
      text: (player|pts_vs_win)
      number_grouping: true
      min_digits: 1
      font_name: druillet
      color: green
      font_size: 10
      anchor_x: middle
      anchor_y: middle
      x: middle
      y: middle - 200
      opacity: 0
      animations:
        show_slide:
        - property: opacity
          value: 0
          duration: 2.5s
        - property: opacity
          value: 1
          duration: 0
          timing: after_previous
        - property: font_size
          value: 150
          duration: .25s
          timing: with_previous 
    - type: image
      image: background

  vs_breakout_lose:
    widgets:
    - type: text
      text: USA
      font_size: 25
      font_name: druillet
      anchor_x: left
      anchor_y: center
      x: left + 55
      y: middle + 200
      color: 008ce5ff
      animations:
        show_slide:
          - property: font_size
            value: 150
            duration: .5s
    - type: text
      text: vs
      font_size: 25
      font_name: druillet
      anchor_x: center
      anchor_y: center
      x: middle - 200
      y: middle + 200
      color: 008ce5ff
      opacity: 0
      animations:
        show_slide:
          - property: opacity
            value: 0
            duration: 1s
          - property: opacity
            value: 1
            duration: 0
            timing: after_previous
          - property: font_size
            value: 150
            duration: .25s
            timing: with_previous
    - type: text
      text: (opponent)
      font_size: 25
      font_name: druillet
      anchor_x: left
      anchor_y: center
      x: middle - 25
      y: middle + 200
      color: 008ce5ff
      opacity: 0
      animations:
        show_slide:
          - property: opacity
            value: 0
            duration: 2s
          - property: opacity
            value: 1
            duration: 0
            timing: after_previous
          - property: font_size
            value: 150
            duration: .25s
            timing: with_previous
    - type: text
      text: PLAYER LOSES
      font_size: 25
      font_name: druillet
      anchor_x: center
      anchor_y: center
      x: middle
      y: middle - 100
      color: red
      opacity: 0
      animations:
        show_slide:
          - property: opacity
            value: 0
            duration: 2.5s
          - property: opacity
            value: 1
            duration: 0
            timing: after_previous
          - property: font_size
            value: 200
            duration: .25s
            timing: with_previous       
    - type: image
      image: background

slide_player:
  mode_vs_breakout_started:
    vs_breakout_intro:
      target: main
      priority: 4000
      expire: 5s
    vs_breakout_mini:
      target: mini
      priority: 4000
  slide_vs_breakout_intro_removed:
    vs_breakout_status:
      target: main
      priority: 4000
  vs_result_win:
    vs_breakout_status:
      target: main
      action: remove
    vs_breakout_win:
      target: main
      expire: 5s
      priority: 4000
  vs_result_lose:
    vs_breakout_status:
      target: main
      action: remove
    vs_breakout_lose:
      target: main
      expire: 5s
      priority: 4000

random_event_player:
  rnd_ball_x:
    - set_ball_x{value: 183}
    - set_ball_x{value: 283}
    - set_ball_x{value: 383}
    - set_ball_x{value: 483}
    - set_ball_x{value: 583}
    - set_ball_x{value: 683}
    - set_ball_x{value: 783}
    - set_ball_x{value: 883}
    - set_ball_x{value: 983}
    - set_ball_x{value: 1083}
    - set_ball_vx{value: 1183}
  rnd_ball_vx:
    - set_ball_vx{value: 10}
    - set_ball_vx{value: 20}
    - set_ball_vx{value: 30}
    - set_ball_vx{value: 40}
    - set_ball_vx{value: 50}
  rnd_cup_x:
    - set_cup_x{value: 383}
    - set_cup_x{value: 483}
    - set_cup_x{value: 583}
    - set_cup_x{value: 683}
    - set_cup_x{value: 783}
    - set_cup_x{value: 883}
    - set_cup_x{value: 983}

variable_player:
  mode_vs_breakout_stopping: # clear VS active bit
    is_in_vs:
      int: 0
      action: set
  mode_vs_breakout_started:
    ball_x:
      int: 683
      action: set
    ball_y:
      int: 700
      action: set
    cup_x:
      int: 683
      action: set
    cup_y:
      int: 75
      action: set
    is_in_vs:
      int: 1
      action: set
  vs_result_win:
    score: current_player.pts_vs_win

  vs_result_win{current_player.opponent == "CANADA"}:   # top left
    has_canada:
      action: set
      int: 1
  vs_result_win{current_player.opponent == "SCOTLAND"}: # top right
    has_scotland:
      action: set
      int: 1
  vs_result_win{current_player.opponent == "IRELAND"}:  # middle left
    has_ireland:
      action: set
      int: 1
  vs_result_win{current_player.opponent == "TOBAGO"}:   # middle right
    has_tobago:
      action: set
      int: 1
  vs_result_win{current_player.opponent == "GERMANY"}:  # bottom left
    has_germany:
      action: set
      int: 1
  set_ball_x:
    ball_x:
      int: (value)
      action: set
  set_ball_y:
    ball_y:
      int: (value)
      action: set
  set_ball_vx:
    ball_vx:
      int: (value)
      action: set
  move_cup_left:
    cup_x:
      int: current_player.cup_x - 50
      action: set
  move_cup_far_left:
    cup_x:
      int: 80
      action: set
  move_cup_right:
    cup_x:
      int: current_player.cup_x + 50
      action: set
  move_cup_far_right:
    cup_x:
      int: 1286
      action: set

