#config_version=5

coils:
  # 48V Coil Driver PCB: A0
  # Bank A (A0-B0)
  c_flipper_right:
    number: A0-B0-0         # PD-16 Address 0, Bank A, Bit 1 for right flipper
    default_pulse_ms: 25
    default_hold_power: .125
  c_slingshot_right:
    number: A0-B0-1
    default_pulse_ms: 5
  c_kicker_mode:
    number: A0-B0-2
    default_pulse_ms: 8

  c_pop_lower:
    number: A0-B0-5 # verified
    default_pulse_ms: 8
  c_pop_upper_left:
    number: A0-B0-6
    default_pulse_ms: 8
  c_pop_upper_right:
    number: A0-B0-7
    default_pulse_ms: 8

  # Bank B (A0-B1)
  
  c_slingshot_left:
    number: A0-B1-1
    default_pulse_ms: 5
  c_slingshot_quarters:
    number: A0-B1-2
    default_pulse_ms: 8 
  c_strike_out:
    number: A0-B1-3
    default_pulse_ms: 20
  c_flipper_left:
    number: A0-B1-4
    default_pulse_ms: 25
    default_hold_power: .125
  c_flipper_upper:
    number: A0-B1-5
    default_pulse_ms: 13
    default_hold_power: .125
  c_kicker_rimrules:
    number: A0-B1-7
    default_pulse_ms: 10


  # 24V Coil Driver PCB: A1-B0
  c_shaker:
    number: A1-B0-0
    default_pulse_ms: 5
    default_hold_power: 0.3
  c_knocker:
    number: A1-B0-1
    default_pulse_ms: 35
    default_hold_power: 0.125
  c_pongcup1:
    number: A1-B0-3
    default_pulse_ms: 500
    default_hold_power: .5
    pulse_events: release_cup1 #, None    # adding this event removes the default pulse_event, which collecting_balls was using to fire the release coils too early.
  c_pongcup2:
    number: A1-B0-2
    default_pulse_ms: 500
    default_hold_power: .5
    pulse_events: release_cup2 #, None   # adding this event removes the default pulse_event, which collecting_balls was using to fire the release coils too early.
  
  # 12V Coil Driver PCB: A1-B1
  # J11
  cl_pop_lower:
    number: A1-B1-0
    allow_enable: true
  cl_pop_right:
    number: A1-B1-1
    allow_enable: true
  cl_pop_left:
    number: A1-B1-2
    allow_enable: true
  c_trough_eject:
    number: A1-B1-3
    default_pulse_ms: 40
    default_hold_power: .5
  c_drain_eject:
    number: A1-B1-4
    default_pulse_ms: 40
    default_hold_power: .5
  cl_start:
    number: A1-B1-5
    allow_enable: true
  c_popo_eject:
    number: A1-B1-6
    default_pulse_ms: 25
    default_hold_power: .5
    pulse_events: eject_popo
  c_quarters:
    number: A1-B1-7
    default_pulse_ms: 25
    default_hold_power: .125

# PD-LED Driver PCB: A2-Bx-x

autofire_coils:
  slingshot_left:
    coil: c_slingshot_left
    switch: s_slingshot_left
  slingshot_right:
    coil: c_slingshot_right
    switch: s_slingshot_right
  pop_lower:
    coil: c_pop_lower
    switch: s_pop_lower
  pop_upper_right:
    coil: c_pop_upper_right
    switch: s_pop_upper_right
  pop_upper_left:
    coil: c_pop_upper_left
    switch: s_pop_upper_left
  slingshot_quarters:
    coil: c_slingshot_quarters
    switch: s_slingshot_quarters
  quarters:
    coil: c_quarters
    switch: s_quarters

