#config_version=5

light_settings:
  default_fade_ms: 250

lights:
  # Chain #1 [J8-19: WS281x Serial Data 0]
  arrow_tavern6:
    start_channel: 2-100
    type: grb
    tags: strip
  arrow_tavern5:
    previous: arrow_tavern6
    type: grb
    tags: strip
  arrow_tavern4:
    previous: arrow_tavern5
    type: grb
    tags: strip
  arrow_tavern3:
    previous: arrow_tavern4
    type: grb
    tags: strip
  arrow_tavern2:
    previous: arrow_tavern3
    type: grb
    tags: strip
  arrow_tavern1:
    previous: arrow_tavern2
    type: grb
    tags: strip
  canada_left:
    previous: arrow_tavern1
    type: grb
    tags: strip
  canada_right:
    previous: canada_left
    type: grb
    tags: strip
  ireland_right:
    previous: canada_right
    type: grb
    tags: strip
  ireland_left:
    previous: ireland_right
    type: grb
    tags: strip
  arrow_popo3:
    previous: ireland_left
    type: grb
    tags: strip
  arrow_popo2:
    previous: arrow_popo3
    type: grb
    tags: strip
  arrow_popo1:
    previous: arrow_popo2
    type: grb
    tags: strip
  germany_left:
    previous: arrow_popo1
    type: grb
    tags: strip
  germany_right:
    previous: germany_left
    type: grb
    tags: strip
  quarters1:
    previous: germany_right
    type: grb
    tags: strip
  quarters2:
    previous: quarters1
    type: grb
    tags: strip
  quarters3:
    previous: quarters2
    type: grb
    tags: strip
  quarters4:
    previous: quarters3
    type: grb
    tags: strip
  quarters5:
    previous: quarters4
    type: grb
    tags: strip
  slingquarters_upper:
    previous: quarters5
    type: grb
    tags: strip
  slingquarters_lower:
    previous: slingquarters_upper
    type: grb
    tags: strip
  2x:
    previous: slingquarters_lower
    type: grb
    tags: strip
  3x:
    previous: 2x
    type: grb
    tags: strip
  4x:
    previous: 3x
    type: grb
    tags: strip
  5x:
    previous: 4x
    type: grb
    tags: strip
  mode_dasboot:
    previous: 5x
    type: grb
    tags: strip
  mode_trojankeg:
    previous: mode_dasboot
    type: grb
    tags: strip
  mode_strikeout:
    previous: mode_trojankeg
    type: grb
    tags: strip
  mode_quarters:
    previous: mode_strikeout
    type: grb
    tags: strip
  mode_longpour:
    previous: mode_quarters
    type: grb
    tags: strip
  mode_volumechug:
    previous: mode_longpour
    type: grb
    tags: strip
  6x:
    previous: mode_volumechug
    type: grb
    tags: strip
  lane_left_outer:
    previous: 6x
    type: grb
    tags: strip
  sausage_save:
    previous: lane_left_outer
    type: grb
    tags: strip
  lane_left_inner:
    previous: sausage_save
    type: grb
    tags: strip
  slingleft_upper:
    previous: lane_left_inner
    type: grb
    tags: strip
  slingleft_lower:
    previous: slingleft_upper
    type: grb
    tags: strip
  flipper_left_outer:
    previous: slingleft_lower
    type: grb
    tags: strip
  flipper_left_inner:
    previous: flipper_left_outer
    type: grb
    tags: strip
  ball_save:
    previous: flipper_left_inner
    type: grb
    tags: strip
  flipper_right_inner:
    previous: ball_save
    type: grb
    tags: strip
  flipper_right_outer:
    previous: flipper_right_inner
    type: grb
    tags: strip
  bad_rams_piss:
    previous: flipper_right_outer
    type: grb
    tags: strip
  slingright_lower:
    previous: bad_rams_piss
    type: grb
    tags: strip
  slingright_upper:
    previous: slingright_lower
    type: grb
    tags: strip
  lane_right_inner:
    previous: slingright_upper
    type: grb
    tags: strip
  lane_right_outer:
    previous: lane_right_inner
    type: grb
    tags: strip
  special:
    previous: lane_right_outer
    type: grb
    tags: strip
  chance:
    previous: special
    type: grb
    tags: strip
  startevent_mode:
    previous: chance
    type: grb
    tags: strip 
  arrow_mode1:
    previous: startevent_mode
    type: grb
    tags: strip
  arrow_mode2:
    previous: arrow_mode1
    type: grb
    tags: strip
  arrow_mode3:
    previous: arrow_mode2
    type: grb
    tags: strip
  arrow_paddle3:
    previous: arrow_mode3
    type: grb
    tags: strip
  arrow_paddle2:
    previous: arrow_paddle3
    type: grb
    tags: strip
  arrow_paddle1:
    previous: arrow_paddle2
    type: grb
    tags: strip
  lock:
    previous: arrow_paddle1
    type: grb
    tags: strip
  arrow_house1:
    previous: lock
    type: grb
    tags: strip
  arrow_house2:
    previous: arrow_house1
    type: grb
    tags: strip
  arrow_house3:
    previous: arrow_house2
    type: grb
    tags: strip
  strikeout_shot:
    previous: arrow_house3
    type: grb
    tags: strip
  strikeout_beer:
    previous: strikeout_shot
    type: grb
    tags: strip
  strikeout_bong:
    previous: strikeout_beer
    type: grb
    tags: strip
  ball1_locked:
    previous: strikeout_bong
    type: grb
    tags: strip
  ball2_locked:
    previous: ball1_locked
    type: grb
    tags: strip
  usa_right:
    previous: ball2_locked
    type: grb
    tags: strip
  usa_left:
    previous: usa_right
    type: grb
    tags: strip
  tobago_left:
    previous: usa_left
    type: grb
    tags: strip
  tobago_right:
    previous: tobago_left
    type: grb
    tags: strip
  scotland_right:
    previous: tobago_right
    type: grb
    tags: strip
  scotland_left:
    previous: scotland_right
    type: grb
    tags: strip
  extra_ball:
    previous: scotland_left
    type: grb
    tags: strip
  arrow_boot1:
    previous: extra_ball
    type: grb
    tags: strip
  arrow_boot2:
    previous: arrow_boot1
    type: grb
    tags: strip
  arrow_boot3:
    previous: arrow_boot2
    type: grb
    tags: strip
  startevent_rimrules:
    previous: arrow_boot3
    type: grb
    tags: strip
  arrow_rimrules1:
    previous: startevent_rimrules
    type: grb
    tags: strip
  arrow_rimrules2:
    previous: arrow_rimrules1
    type: grb
    tags: strip
  arrow_rimrules3:
    previous: arrow_rimrules2
    type: grb
    tags: strip

# Chain 2 - WS281x Serial Channel 2 (PD-LED J8-17)
  arrow_horseshoe3:
    start_channel: 2-450
    type: grb
    tags: strip
  arrow_horseshoe2:
    previous: arrow_horseshoe3
    type: grb
    tags: strip
  arrow_horseshoe1:
    previous: arrow_horseshoe2
    type: grb
    tags: strip
  gi_left4:
    previous: arrow_horseshoe1
    type: grb
    tags: gi 
  gi_left3:
    previous: gi_left4
    type: grb
    tags: gi 
  gi_left2:
    previous: gi_left3
    type: grb
    tags: gi 
  gi_left1:
    previous: gi_left2
    type: grb
    tags: gi 
  gi_right1:
    previous: gi_left1
    type: grb
    tags: gi
  gi_right2:
    previous: gi_right1
    type: grb
    tags: gi
  gi_right3:
    previous: gi_right2
    type: grb
    tags: gi 
  gi_right4:
    previous: gi_right3
    type: grb
    tags: gi
  gi_back6:
    previous: gi_right4
    type: grb
    tags: back, munichfill6
  gi_back5:
    previous: gi_back6
    type: grb
    tags: back, munichfill5, munichfill6
  gi_back4:
    previous: gi_back5
    type: grb
    tags: back, munichfill4, munichfill5, munichfill6
  gi_back3:
    previous: gi_back4
    type: grb
    tags: back, munichfill3, munichfill4, munichfill5, munichfill6
  gi_back2:
    previous: gi_back3
    type: grb
    tags: back, munichfill2, munichfill3, munichfill4, munichfill5, munichfill6
  gi_back1:
    previous: gi_back2
    type: grb
    tags: back, munichfill1, munichfill2, munichfill3, munichfill4, munichfill5, munichfill6
  tavern_sign1:
    previous: gi_back1
    type: grb
    tags: tavern 
  tavern_sign2:
    previous: tavern_sign1
    type: grb
    tags: tavern
  tavern_inside:
    previous: tavern_sign2
    type: grb
    tags: tavern  
  
  # lights hooked to coil driver
  l_pop_lower:
    number: cl_pop_lower
    platform: drivers
  l_pop_right:
    number: cl_pop_right
    platform: drivers
  l_pop_left:
    number: cl_pop_left
    platform: drivers
  l_start:
    number: cl_start
    platform: drivers