#config_version=5

light_settings:
  default_fade_ms: 150

lights:
  # Chain #1 [J8-19: WS281x Serial Data 0]
  arrow_tavern6:
    start_channel: 2-0
    type: grb
    tags: playfield
  arrow_tavern5:
    previous: arrow_tavern6
    type: grb
    tags: playfield
  arrow_tavern4:
    previous: arrow_tavern5
    type: grb
    tags: playfield
  arrow_tavern3:
    previous: arrow_tavern4
    type: grb
    tags: playfield
  arrow_tavern2:
    previous: arrow_tavern3
    type: grb
    tags: playfield
  arrow_tavern1:
    previous: arrow_tavern2
    type: grb
    tags: playfield
  canada_left:
    previous: arrow_tavern1
    type: grb
    tags: playfield
  canada_right:
    previous: canada_left
    type: grb
    tags: playfield
  ireland_right:
    previous: canada_right
    type: grb
    tags: playfield
  ireland_left:
    previous: ireland_right
    type: grb
    tags: playfield
  arrow_popo3:
    previous: ireland_left
    type: grb
    tags: playfield
  arrow_popo2:
    previous: arrow_popo3
    type: grb
    tags: playfield
  arrow_popo1:
    previous: arrow_popo2
    type: grb
    tags: playfield
  germany_left:
    previous: arrow_popo1
    type: grb
    tags: playfield
  germany_right:
    previous: germany_left
    type: grb
    tags: playfield
  quarters1:
    previous: germany_right
    type: grb
    tags: playfield
  quarters2:
    previous: quarters1
    type: grb
    tags: playfield
  quarters3:
    previous: quarters2
    type: grb
    tags: playfield
  quarters4:
    previous: quarters3
    type: grb
    tags: playfield
  quarters5:
    previous: quarters4
    type: grb
    tags: playfield
  slingquarters_upper:
    previous: quarters5
    type: grb
    tags: playfield
  slingquarters_lower:
    previous: slingquarters_upper
    type: grb
    tags: playfield
  2x:
    previous: slingquarters_lower
    type: grb
    tags: playfield
  3x:
    previous: 2x
    type: grb
    tags: playfield
  4x:
    previous: 3x
    type: grb
    tags: playfield
  5x:
    previous: 4x
    type: grb
    tags: playfield
  mode_dasboot:
    previous: 5x
    type: grb
    tags: playfield
  mode_trojankeg:
    previous: mode_dasboot
    type: grb
    tags: playfield
  mode_strikeout:
    previous: mode_trojankeg
    type: grb
    tags: playfield
  mode_quarters:
    previous: mode_strikeout
    type: grb
    tags: playfield
  mode_longpour:
    previous: mode_quarters
    type: grb
    tags: playfield
  mode_volumechug:
    previous: mode_longpour
    type: grb
    tags: playfield
  6x:
    previous: mode_volumechug
    type: grb
    tags: playfield
  lane_left_outer:
    previous: 6x
    type: grb
    tags: playfield
  sausage_save:
    previous: lane_left_outer
    type: grb
    tags: playfield
  lane_left_inner:
    previous: sausage_save
    type: grb
    tags: playfield
  slingleft_upper:
    previous: lane_left_inner
    type: grb
    tags: playfield
  slingleft_lower:
    previous: slingleft_upper
    type: grb
    tags: playfield
  flipper_left_outer:
    previous: slingleft_lower
    type: grb
    tags: playfield
  flipper_left_inner:
    previous: flipper_left_outer
    type: grb
    tags: playfield
  bong_left1:
    previous: flipper_left_inner
    type: grb
    tags: playfield, bong
  bong_left2:
    previous: bong_left1
    type: grb
    tags: playfield, bong
  bong_left3:
    previous: bong_left2
    type: grb
    tags: playfield, bong
  bong_left4:
    previous: bong_left3
    type: grb
    tags: playfield, bong
  bong_left5:
    previous: bong_left4
    type: grb
    tags: playfield, bong
  bong_left6:
    previous: bong_left5
    type: grb
    tags: playfield, bong
  bong_right1:
    previous: bong_left6
    type: grb
    tags: playfield, bong
  bong_right2:
    previous: bong_right1
    type: grb
    tags: playfield, bong
  bong_right3:
    previous: bong_right2
    type: grb
    tags: playfield, bong
  bong_right4:
    previous: bong_right3
    type: grb
    tags: playfield, bong
  bong_right5:
    previous: bong_right4
    type: grb
    tags: playfield, bong
  bong_right6:
    previous: bong_right5
    type: grb
    tags: playfield, bong
  ball_save:
    previous: bong_right6
    type: grb
    tags: playfield
  flipper_right_inner:
    previous: ball_save
    type: grb
    tags: playfield
  flipper_right_outer:
    previous: flipper_right_inner
    type: grb
    tags: playfield
  bad_rams_piss:
    previous: flipper_right_outer
    type: grb
    tags: playfield
  slingright_lower:
    previous: bad_rams_piss
    type: grb
    tags: playfield
  slingright_upper:
    previous: slingright_lower
    type: grb
    tags: playfield
  lane_right_inner:
    previous: slingright_upper
    type: grb
    tags: playfield
  lane_right_outer:
    previous: lane_right_inner
    type: grb
    tags: playfield
  special:
    previous: lane_right_outer
    type: grb
    tags: playfield
  chance:
    previous: special
    type: grb
    tags: playfield
  startevent_mode:
    previous: chance
    type: grb
    tags: playfield 
  arrow_mode1:
    previous: startevent_mode
    type: grb
    tags: playfield
  arrow_mode2:
    previous: arrow_mode1
    type: grb
    tags: playfield
  arrow_mode3:
    previous: arrow_mode2
    type: grb
    tags: playfield
  arrow_upf3:
    previous: arrow_mode3
    type: grb
    tags: playfield
  arrow_upf2:
    previous: arrow_upf3
    type: grb
    tags: playfield
  arrow_upf1:
    previous: arrow_upf2
    type: grb
    tags: playfield
  lock:
    previous: arrow_upf1
    type: grb
    tags: playfield
  arrow_house1:
    previous: lock
    type: grb
    tags: playfield
  arrow_house2:
    previous: arrow_house1
    type: grb
    tags: playfield
  arrow_house3:
    previous: arrow_house2
    type: grb
    tags: playfield
  strikeout_shot:
    previous: arrow_house3
    type: grb
    tags: playfield
  strikeout_beer:
    previous: strikeout_shot
    type: grb
    tags: playfield
  strikeout_bong:
    previous: strikeout_beer
    type: grb
    tags: playfield
  ball1_locked:
    previous: strikeout_bong
    type: grb
    tags: playfield
  ball2_locked:
    previous: ball1_locked
    type: grb
    tags: playfield
  usa_right:
    previous: ball2_locked
    type: grb
    tags: playfield
  usa_left:
    previous: usa_right
    type: grb
    tags: playfield
  tobago_left:
    previous: usa_left
    type: grb
    tags: playfield
  tobago_right:
    previous: tobago_left
    type: grb
    tags: playfield
  scotland_right:
    previous: tobago_right
    type: grb
    tags: playfield
  scotland_left:
    previous: scotland_right
    type: grb
    tags: playfield
  extra_ball:
    previous: scotland_left
    type: grb
    tags: playfield
  arrow_boot1:
    previous: extra_ball
    type: grb
    tags: playfield
  arrow_boot2:
    previous: arrow_boot1
    type: grb
    tags: playfield
  arrow_boot3:
    previous: arrow_boot2
    type: grb
    tags: playfield
  startevent_rimrules:
    previous: arrow_boot3
    type: grb
    tags: playfield
  arrow_rimrules1:
    previous: startevent_rimrules
    type: grb
    tags: playfield
  arrow_rimrules2:
    previous: arrow_rimrules1
    type: grb
    tags: playfield
  arrow_rimrules3:
    previous: arrow_rimrules2
    type: grb
    tags: playfield
# ^^ Chain 1 ^^ 92 RGBs, 276 LEDs


# Chain 2 - WS281x Serial Channel 2 (PD-LED J8-17)
  arrow_horseshoe3:
    start_channel: 2-276
    type: grb
    tags: playfield
  arrow_horseshoe2:
    previous: arrow_horseshoe3
    type: grb
    tags: playfield
  arrow_horseshoe1:
    previous: arrow_horseshoe2
    type: grb
    tags: playfield
  gi_left4:
    previous: arrow_horseshoe1
    type: grb
    tags: gi 
  gi_left3:
    previous: gi_left4
    type: grb
    tags: gi 
  gi_left2:
    previous: gi_left3
    type: grb
    tags: gi 
  gi_left1:
    previous: gi_left2
    type: grb
    tags: gi 
  gi_right1:
    previous: gi_left1
    type: grb
    tags: gi
  gi_right2:
    previous: gi_right1
    type: grb
    tags: gi
  gi_right3:
    previous: gi_right2
    type: grb
    tags: gi 
  gi_right4:
    previous: gi_right3
    type: grb
    tags: gi
  gi_back6:
    previous: gi_right4
    type: grb
    tags: gi, munichfill6
  gi_back5:
    previous: gi_back6
    type: grb
    tags: gi, munichfill5, munichfill6
  gi_back4:
    previous: gi_back5
    type: grb
    tags: gi, munichfill4, munichfill5, munichfill6
  gi_back3:
    previous: gi_back4
    type: grb
    tags: gi, munichfill3, munichfill4, munichfill5, munichfill6
  gi_back2:
    previous: gi_back3
    type: grb
    tags: gi, munichfill2, munichfill3, munichfill4, munichfill5, munichfill6
  gi_back1:
    previous: gi_back2
    type: grb
    tags: gi, munichfill1, munichfill2, munichfill3, munichfill4, munichfill5, munichfill6
  # ^^ Chain #2, 17 RGBs, 51 LEDs

  # Chain #3, 238 RGBs, 714 LEDs
  topper1:
    start_channel: 2-327
    type: grb
    tags: topper
  topper2:
    previous: topper1
    type: grb
    tags: topper
  topper3:
    previous: topper2
    type: grb
    tags: topper
  topper4:
    previous: topper3
    type: grb
    tags: topper
  topper5:
    previous: topper4
    type: grb
    tags: topper
  topper6:
    previous: topper5
    type: grb
    tags: topper
  topper7:
    previous: topper6
    type: grb
    tags: topper
  topper8:
    previous: topper7
    type: grb
    tags: topper
  topper9:
    previous: topper8
    type: grb
    tags: topper
  topper10:
    previous: topper9
    type: grb
    tags: topper
  topper11:
    previous: topper10
    type: grb
    tags: topper
  topper12:
    previous: topper11
    type: grb
    tags: topper
  topper13:
    previous: topper12
    type: grb
    tags: topper
  topper14:
    previous: topper13
    type: grb
    tags: topper
  topper15:
    previous: topper14
    type: grb
    tags: topper
  topper16:
    previous: topper15
    type: grb
    tags: topper
  topper17:
    previous: topper16
    type: grb
    tags: topper
  topper18:
    previous: topper17
    type: grb
    tags: topper
  topper19:
    previous: topper18
    type: grb
    tags: topper
  topper20:
    previous: topper19
    type: grb
    tags: topper
  topper21:
    previous: topper20
    type: grb
    tags: topper
  topper22:
    previous: topper21
    type: grb
    tags: topper
  topper23:
    previous: topper22
    type: grb
    tags: topper
  topper24:
    previous: topper23
    type: grb
    tags: topper
  topper25:
    previous: topper24
    type: grb
    tags: topper
  topper26:
    previous: topper25
    type: grb
    tags: topper
  topper27:
    previous: topper26
    type: grb
    tags: topper
  topper28:
    previous: topper27
    type: grb
    tags: topper
  topper29:
    previous: topper28
    type: grb
    tags: topper
  topper30:
    previous: topper29
    type: grb
    tags: topper
  topper31:
    previous: topper30
    type: grb
    tags: topper
  topper32:
    previous: topper31
    type: grb
    tags: topper
  topper33:
    previous: topper32
    type: grb
    tags: topper
  topper34:
    previous: topper33
    type: grb
    tags: topper
  topper35:
    previous: topper34
    type: grb
    tags: topper
  topper36:
    previous: topper35
    type: grb
    tags: topper
  topper37:
    previous: topper36
    type: grb
    tags: topper
  topper38:
    previous: topper37
    type: grb
    tags: topper
  topper39:
    previous: topper38
    type: grb
    tags: topper
  topper40:
    previous: topper39
    type: grb
    tags: topper
  topper41:
    previous: topper40
    type: grb
    tags: topper
  topper42:
    previous: topper41
    type: grb
    tags: topper
  topper43:
    previous: topper42
    type: grb
    tags: topper
  topper44:
    previous: topper43
    type: grb
    tags: topper
  topper45:
    previous: topper44
    type: grb
    tags: topper
  topper46:
    previous: topper45
    type: grb
    tags: topper
  topper47:
    previous: topper46
    type: grb
    tags: topper
  topper48:
    previous: topper47
    type: grb
    tags: topper
  topper49:
    previous: topper48
    type: grb
    tags: topper
  topper50:
    previous: topper49
    type: grb
    tags: topper
  topper51:
    previous: topper50
    type: grb
    tags: topper
  topper52:
    previous: topper51
    type: grb
    tags: topper
  topper53:
    previous: topper52
    type: grb
    tags: topper
  topper54:
    previous: topper53
    type: grb
    tags: topper
  topper55:
    previous: topper54
    type: grb
    tags: topper
  topper56:
    previous: topper55
    type: grb
    tags: topper
  topper57:
    previous: topper56
    type: grb
    tags: topper
  topper58:
    previous: topper57
    type: grb
    tags: topper
  topper59:
    previous: topper58
    type: grb
    tags: topper
  topper60:
    previous: topper59
    type: grb
    tags: topper
  topper61:
    previous: topper60
    type: grb
    tags: topper
  topper62:
    previous: topper61
    type: grb
    tags: topper
  topper63:
    previous: topper62
    type: grb
    tags: topper
  topper64:
    previous: topper63
    type: grb
    tags: topper
  topper65:
    previous: topper64
    type: grb
    tags: topper
  topper66:
    previous: topper65
    type: grb
    tags: topper
  topper67:
    previous: topper66
    type: grb
    tags: topper
  topper68:
    previous: topper67
    type: grb
    tags: topper
  topper69:
    previous: topper68
    type: grb
    tags: topper
  topper70:
    previous: topper69
    type: grb
    tags: topper
  topper71:
    previous: topper70
    type: grb
    tags: topper
  topper72:
    previous: topper71
    type: grb
    tags: topper
  topper73:
    previous: topper72
    type: grb
    tags: topper
  topper74:
    previous: topper73
    type: grb
    tags: topper
  topper75:
    previous: topper74
    type: grb
    tags: topper
  topper76:
    previous: topper75
    type: grb
    tags: topper
  topper77:
    previous: topper76
    type: grb
    tags: topper
  topper78:
    previous: topper77
    type: grb
    tags: topper
  topper79:
    previous: topper78
    type: grb
    tags: topper
  topper80:
    previous: topper79
    type: grb
    tags: topper
  topper81:
    previous: topper80
    type: grb
    tags: topper
  topper82:
    previous: topper81
    type: grb
    tags: topper
  topper83:
    previous: topper82
    type: grb
    tags: topper
  topper84:
    previous: topper83
    type: grb
    tags: topper
  topper85:
    previous: topper84
    type: grb
    tags: topper
  topper86:
    previous: topper85
    type: grb
    tags: topper
  topper87:
    previous: topper86
    type: grb
    tags: topper
  topper88:
    previous: topper87
    type: grb
    tags: topper
  topper89:
    previous: topper88
    type: grb
    tags: topper
  topper90:
    previous: topper89
    type: grb
    tags: topper
  topper91:
    previous: topper90
    type: grb
    tags: topper
  topper92:
    previous: topper91
    type: grb
    tags: topper
  topper93:
    previous: topper92
    type: grb
    tags: topper
  topper94:
    previous: topper93
    type: grb
    tags: topper
  topper95:
    previous: topper94
    type: grb
    tags: topper
  topper96:
    previous: topper95
    type: grb
    tags: topper
  topper97:
    previous: topper96
    type: grb
    tags: topper
  topper98:
    previous: topper97
    type: grb
    tags: topper
  topper99:
    previous: topper98
    type: grb
    tags: topper
  topper100:
    previous: topper99
    type: grb
    tags: topper

 
  
  # lights hooked to coil driver
  l_pop_lower:
    number: cl_pop_lower
    tags: playfield
    platform: drivers
  l_pop_right:
    number: cl_pop_right
    tags: playfield
    platform: drivers
  l_pop_left:
    number: cl_pop_left
    tags: playfield
    platform: drivers
  l_start:
    number: cl_start
    platform: drivers