#config_version=5

sounds:
  introrepeat:
    file: introrepeat1.wav
    track: music
    volume: .5
  intro:
    file: intro1.wav
    track: music
    volume: 1.0
  voice_newplayer:
    file: newplayer.wav
    track: voice
    volume: 1.0
  voice_welcome:
    file: welcome.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: 1.0 sec
        release: 3.0 sec

  # All 5 theme mode rounds
  themedrinkonme:
    file: themedrinkonme.wav
    track: music
    volume: 1.0
  themehardasarock:
    file: themehardasarock.wav
    track: music
    volume: 1.0
  themejungleboogie:
    file: themejungleboogie.wav
    track: music
    volume: 1.0
  themealcohol:
    file: themealcohol.wav
    track: music
    volume: 1.0
  themebeer:
    file: themebeer.wav
    track: music
    volume: 1.0
  themebeerformyhorses:
    file: themebeerformyhorses.wav
    track: music
    volume: 1.0
  themebyob:
    file: themebyob.wav
    track: music
    volume: 1.0
  themecomininhot:
    file: themecomininhot.wav
    track: music
    volume: 1.0
  
  # other
  music_wasted:
    file: soundtrackwasted.wav
    track: music
    volume: 1.0


  # DAS BOOT
  music_bubbles:
    file: dasbootthemebubbles.wav
    track: voice
    volume: 1.0

  
  voice_ohyea:
    file: buckcherry-ohyea.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -18db
        release_point: 1.0 sec
        release: 3.0 sec

  voice_vs_win:
    file: vs_win.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -18db
        release_point: 1.0 sec
        release: 3.0 sec
  voice_vs_lose:
    file: death-noo.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -18db
        release_point: 1.0 sec
        release: 3.0 sec
  voice_sink1left:
    file: notthatdrunk2.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -18db
        release_point: 1.0 sec
        release: 3.0 sec
  voice_nicesink1:
    file: Jay-NiceSink1.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -3db
        release_point: 1.0 sec
        release: 3.0 sec
  voice_nicesink2:
    file: Jay-NiceSink2.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -3db
        release_point: 1.0 sec
        release: 3.0 sec
  voice_dirtyharry:
    file: dirtyharry.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -6db
        release_point: 1.0 sec
        release: 3.0 sec
  voice_frustrating:
    file: frustrating.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -3db
        release_point: 1.0 sec
        release: 3.0 sec
  voice_emchammered:
    file: emchammered.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -18db
        release_point: 1.0 sec
        release: 3.0 sec
  voice_goodnightpopo:
    file: goodnightpopo.wav
    track: voice
    volume: 1.0
  voice_oprecipe:
    file: oprecipe.wav
    track: voice
    volume: 1.0  
  voice_betterwhendrunk:
    file: betterwhendrunk.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  # Longpour is custom from Derek/BL (below)
  voice_quarters_intro:
    file: modeintro-quarters.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_strikeout_intro:
    file: modeintro-strikeout.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_volumechug_intro:
    file: modeintro-volumechug.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_trojankeg_intro:
    file: modeintro-trojankeg.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_dasboot_intro:
    file: modeintro-dasboot.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_cheers:
    file: cheers.wav
    track: voice
    volume: 1.0   
  voice_eyeofjew:
    file: eyeofthejew1.wav
    track: voice
    volume: 1.0
  voice_10meters:
    file: 10meters.wav
    track: voice
    volume: 1.0
  voice_20meters:
    file: 20meters.wav
    track: voice
    volume: 1.0 
  voice_30meters:
    file: 30meters.wav
    track: voice
    volume: 1.0
  voice_soberasabird:
    file: soberasabird.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_handsomemf_clean:
    file: handsome_mf_clean.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_handsomemf_adult:
    file: handsome_mf_adult.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_tavern:
    file: tavern1.wav
    track: voice
    volume: 1.0
    #ducking:
    #    target: music
    #    delay: 0
    #    attack: 0.3 sec
    #    attenuation: -50db
    #    release_point: .5 sec
    #    release: 1.5 sec
  
  voice_yodel:
    file: yodel1.wav
    track: voice
    volume: .5

  # death clips  
  voice_drain_cantdrinkabeer:
    file: death-cantdrinkabeer.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_drain_firstbeer:
    file: death-firstbeer.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_drain_nipple:
    file: death-nipple.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_gameover:
    file: death-stableboy.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_beerfest:
    file: dasboot-beerfest.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec
  voice_bootmegabonus:
    file: Jay-BootMegaBonus.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -6db
        release_point: .5 sec
        release: 1.5 sec
  voice_flipperflop_active:
    file: Jay-FlippersFlopped.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -6db
        release_point: .5 sec
        release: 1.5 sec
  voice_multiball:
    file: Jay-MunichMultiball.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -6db
        release_point: .5 sec
        release: 1.5 sec
  voice_multiball_popo:
    file: Jay-Multiball.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -6db
        release_point: .5 sec
        release: 1.5 sec
  voice_spelledbeer:
    file: Jay-SpelledBeer.wav
    track: voice
    volume: 1.0
    # ducking:
    #     target: music
    #     delay: 0
    #     attack: 0.3 sec
    #     attenuation: -50db
    #     release_point: .5 sec
    #     release: 1.5 sec

  voice_longpour_intro:
    file: Jay-Longpour.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .5 sec
        release: 1.5 sec

  voice_volumechug_megabonus:
    file: Jay-VolumeChugMegaBonus.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -10db
        release_point: .5 sec
        release: 1.5 sec
  voice_trojankeg_megabonus:
    file: Jay-TrojanKegMegaBonus.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -10db
        release_point: .5 sec
        release: 1.5 sec
  voice_hitthekeg:
    file: Jay-HitTheKeg.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -10db
        release_point: .5 sec
        release: 1.5 sec
  voice_hitthesaucers_multiball:
    file: Jay-HitTheSaucersForMultiball.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -5db
        release_point: .5 sec
        release: 1.5 sec
  voice_hitthesaucers:
    file: Jay-HitTheSaucers.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -5db
        release_point: .5 sec
        release: 1.5 sec
  voice_redsolocup:
    file: redsolocup.wav
    track: voice
    volume: 1.0
    
  voice_hurryup:
    file: Jay-HurryUp.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0 sec
        attenuation: -10db
        release_point: .1 sec
        release: 1 sec
  voice_letsgotoschnitzengiggle:
    file: Derek-Schnitz.wav
    track: voice
    volume: 1.0
  voice_shoottheboot:
    file: Jay-ShootTheBoot.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -50db
        release_point: .25 sec
        release: .25 sec
  voice_shootthedrinkoramp:
    file: Derek-ShootTheDrinkoRamp.wav
    track: voice
    volume: 1.0
    ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: -10db
        release_point: .5 sec
        release: 1.5 sec
  voice_spelledmunich:
    file: Derek-MunichBonus.wav
    track: voice
    volume: 1.0

  
  sfx_pongcup:
    file: pongcup.wav
    track: sfx
    volume: 1.0
  sfx_cancrush:
    file: cancrush.wav
    track: sfx
    volume: 1.0

    # VS sounds
  crowd:
    file: crowd.wav
    track: music
    volume: 1.0
  winner_usa:
    file: winnerusa.wav
    track: voice
    volume: 1.0
  boom_x4:
    file: boom_x4.wav
    track: sfx
    volume: 1.0  