#config_version=5
##! mode: field

mode:
  start_events: start_mode_field
  stop_events: stop_mode_field
  priority: 300

config:
  - mug.yaml
  - qualify.yaml

timers:
  start_vs_delay:
    start_value: 1
    end_value: 0
    direction: down
    tick_interval: .1s
    control_events:
      - action: restart
        event: selected_vs_alltargets
      - action: restart
        event: selected_vs_breakout
      # Add new VS challenges here

sound_player:
  mode_field_started{players[0].is_welcome_played == 0}:
    voice_welcome:
      action: play
      loops: 0
      events_when_stopped: welcome_played
  welcome_played:
    introrepeat:
      action: play
      track: music
      loops: -1
  mode_field_started{players[0].is_welcome_played == 1}:
    introrepeat:
      action: play
      track: music
      loops: -1
  mode_field_will_stop:
    introrepeat:
      action: stop
  play_betterwhendrunk_and_eject:
    voice_betterwhendrunk:
      action: play
      events_when_stopped: kicker_mode_eject
  play_rimrules_and_eject:
    rimrules:
      action: play
      events_when_stopped: kicker_rimrules_eject
  mode_vs_alltargets_stopped:
    introrepeat:
      action: play
      loops: -1
  mode_vs_breakout_stopped:
    introrepeat:
      action: play
      loops: -1

# Field, and any of the Game Modes (Quarters, Strike Out, etc.) must implement their own listeners on shot_kicker_mode_hit or shot_kicker_rimrules_hit.
event_player:
  shot_kicker_mode_hit{(current_player.is_in_vs == 0) and (device.counters.count_mug_lights.value >= 14)}: launch_random_game_mode
  shot_kicker_mode_hit{(current_player.is_in_vs == 0) and (device.counters.count_mug_lights.value < 14)}: vs_or_play_betterwhendrunk_and_eject
  shot_kicker_rimrules_hit{device.counters.count_mug_lights.value >= 14}: launch_random_game_mode
  shot_kicker_rimrules_hit{(current_player.is_in_vs == 0) and (device.counters.count_mug_lights.value < 14)}: vs_or_play_rimrules_and_eject
  selected_opponent_canada: vs_select_challenge
  selected_opponent_scotland: vs_select_challenge
  selected_opponent_ireland: vs_select_challenge
  selected_opponent_tobago: vs_select_challenge
  selected_opponent_germany: vs_select_challenge
  timer_start_vs_delay_complete: (current_player.selected_vs)
  
random_event_player:
  launch_random_game_mode{current_player.has_longpour==0 or current_player.has_quarters==0 or current_player.has_strikeout==0}:
    events:
      - start_mode_longpour
      - start_mode_quarters
      - start_mode_strikeout
  launch_random_game_mode{(current_player.has_longpour==1 and current_player.has_quarters==1 and current_player.has_strikeout==1) and (current_player.has_volumechug==0 or current_player.has_trojankeg==0)}:
    events:
      - start_mode_volumechug
      - start_mode_trojankeg
  launch_random_game_mode{(current_player.has_longpour==1 and current_player.has_quarters==1 and current_player.has_strikeout==1 and current_player.has_volumechug==1 and current_player.has_trojankeg==1)}:
    events:
      - start_mode_dasboot  # Wizard Mode!
  vs_or_play_betterwhendrunk_and_eject:
    events:
      - vs_select_opponent  # after opponent and challenge are randomly set (player var strings are good), it starts the selected VS challenge
      - play_betterwhendrunk_and_eject
  vs_or_play_rimrules_and_eject:
    events:
      - vs_select_opponent
      - play_rimrules_and_eject
  # select opponent to play
  vs_select_opponent{current_player.has_germany == 0}:
    events:
      - selected_opponent_canada
      - selected_opponent_scotland
      - selected_opponent_ireland
      - selected_opponent_tobago
  vs_select_opponent{current_player.has_canada==1 and current_player.has_scotland==1 and current_player.has_ireland==1 and current_player.has_tobago==1}:
    events:
      - selected_opponent_germany
  vs_select_challenge:
    events:
      - selected_vs_alltargets
      - selected_vs_breakout

show_player:
  mode_field_started:
    show_qualifying:
      speed: 4
  qualified_for_mode_selection:
    show_qualifying:
      action: stop

variable_player:
  welcome_played:
    is_welcome_played:
      int: 1
      action: set
  
  # selecting opponent
  selected_opponent_canada:
    opponent:
      string: CANADA
      action: set
    opponent_left:
      string: canada_left
      action: set
    opponent_right:
      string: canada_right
      action: set
  selected_opponent_scotland:
    opponent:
      string: SCOTLAND
      action: set
    opponent_left:
      string: scotland_left
      action: set
    opponent_right:
      string: scotland_right
      action: set
  selected_opponent_ireland:
    opponent:
      string: IRELAND
      action: set
    opponent_left:
      string: ireland_left
      action: set
    opponent_right:
      string: ireland_right
      action: set
  selected_opponent_tobago:
    opponent:
      string: TOBAGO
      action: set
    opponent_left:
      string: tobago_left
      action: set
    opponent_right:
      string: tobago_right
      action: set
  selected_opponent_germany:
    opponent:
      string: GERMANY
      action: set
    opponent_left:
      string: germany_left
      action: set
    opponent_right:
      string: germany_right
      action: set
  
  # selecting challenges
  selected_vs_alltargets:
    selected_vs:
      string: start_mode_vs_alltargets
      action: set
  selected_vs_breakout:
    selected_vs:
      string: start_mode_vs_breakout
      action: set